### PR TITLE
Fix `cannot open lib/biome.sh: No such file`

### PR DESCRIPTION
**Pull request by skanehira**
Fix this error when I use workdir

```
Run $GITHUB_ACTION_PATH/script.sh
  $GITHUB_ACTION_PATH/script.sh
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    WORKING_DIRECTORY: cdk
    SSH_KEY: ***
  
    PNPM_HOME: /home/runner/setup-pnpm/node_modules/.bin
    INPUT_GITHUB_TOKEN: ***
    INPUT_WORKDIR: cdk
    INPUT_TOOL_NAME: Biome
    INPUT_LEVEL: warning
    INPUT_REPORTER: github-pr-review
    INPUT_FILTER_MODE: nofilter
    INPUT_FAIL_ON_ERROR: true
    INPUT_REVIEWDOG_FLAGS: 
    INPUT_BIOME_FLAGS: .
/home/runner/work/_actions/mongolyy/reviewdog-action-biome/v1/script.sh: 4: .: cannot open lib/biome.sh: No such file
```

### CODE REVIEW

**Review by mongolyy — APPROVED** [review]
thanks!!

**Comment by mongolyy** [comment]
@skanehira 
Thanks for your first contribution.

I think the reason for the failure of [test github action](https://github.com/mongolyy/reviewdog-action-biome/actions/runs/8406833754/job/23021221099?pr=35) is that the existing configuration is not authoritative enough.
I will check with you later, but you are welcome to handle this on your end.

[test shell script](https://github.com/mongolyy/reviewdog-action-biome/actions/runs/8406833753/job/23021185135?pr=35) may not be a concern once the test results are unstable.
I'll check it later on my end.

**Comment by mongolyy** [comment]
@skanehira 
I did some research. #36

If not forking, the current settings seemed to work fine. 987e6d1

The required permissions were as follows. 99de72a
Could you please add the permission settings as well and push?

**Comment by skanehira** [comment]
> @skanehira I did some research. #36
> 
> If not forking, the current settings seemed to work fine. [987e6d1](https://github.com/mongolyy/reviewdog-action-biome/commit/987e6d1b3b4e5a6a44427a7301087c1b85681976)
> 
> The required permissions were as follows. [99de72a](https://github.com/mongolyy/reviewdog-action-biome/commit/99de72aff37e433573cef991d427b94bb5d47b02) Could you please add the permission settings as well and push?

Thank you :)
Added permissions

**Comment by mongolyy** [comment]
> Added permissions

Thank you for your response.
However, it doesn't seem to be working.
https://github.com/mongolyy/reviewdog-action-biome/actions/runs/8410034096/job/23034283589

I see in the log that the check permission is set to read.
2024-03-25_08h32_03

I will investigate today why this is happening.
I'm assuming it's a result of the settings in github, but if you know anything about it on your end, I'd appreciate it if you could let me know!

**Comment by skanehira** [comment]
> > Added permissions
> 
> Thank you for your response. However, it doesn't seem to be working. https://github.com/mongolyy/reviewdog-action-biome/actions/runs/8410034096/job/23034283589
> 
> I see in the log that the check permission is set to read. 2024-03-25_08h32_03
> 
> I will investigate today why this is happening. I'm assuming it's a result of the settings in github, but if you know anything about it on your end, I'd appreciate it if you could let me know!

Humm...
I try added this settings but it didn't works.
I'll take a look later 🙏 

```yaml
      pull-requests: write
      checks: write
      contents: read
```

**Comment by mongolyy** [comment]
@skanehira 
> I try added this settings but it didn't works.

Thank you for trying.
I think it is difficult to give write permission for forked repositories with the current trigger.
https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token

Need to change test to fix this problem, but difficult to do right away.
I'm not sure how to fix this problem.

On the other hand, we think this defect should be resolved as soon as possible.
Since we have confirmed that the test succeeds even in #36, we are willing to tolerate the fact that the test is failing.

If you can revert the changes in `.github/workflows/test-action.yml`, I will approve and merge this.

**Comment by skanehira** [comment]
> @skanehira
> 
> > I try added this settings but it didn't works.
> 
> Thank you for trying. I think it is difficult to give write permission for forked repositories with the current trigger. https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
> 
> Need to change test to fix this problem, but difficult to do right away. I'm not sure how to fix this problem.
> 
> On the other hand, we think this defect should be resolved as soon as possible. Since we have confirmed that the test succeeds even in #36, we are willing to tolerate the fact that the test is failing.
> 
> If you can revert the changes in `.github/workflows/test-action.yml`, I will approve and merge this.

@mongolyy Thank you :)
I removed permissions

**Pull request merged**
